name: Publish

on:
  workflow_dispatch: {}

jobs:
  publish-packages:
    name: Publish Package
    if: github.ref_name == github.event.repository.default_branch
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: '1'
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - name: Use Node.js 24
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # 5.0.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: YARN_ENABLE_COLORS=true yarn install
      - name: Publish packages to npm
        run: |
          npm --version
          npm publish
